name: Release

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  create-and-publish-release:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build and Deploy
        run:
          REVISION=$(echo ${{ github.ref_name }} | sed -E "s/v(.+)/\1/");
          mvn deploy -B -Drevision=$REVISION -s $GITHUB_WORKSPACE/settings.xml;
        env:
          GITHUB_TOKEN: ${{ github.token }}


      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: keepachangelog.toml
          args: --tag ${{ github.ref_name }}
        env:
          OUTPUT: CHANGELOG.md

      - name: Push Changelog
        run:
          git commit -am "generate changelog for version ${{ github.ref_name }}" --;
          git push;
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create GitHub release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: target/*.jar
